import React from 'react'

import './globals.css'

// metadata is read by bini-router at build time and injected into index.html.
// It is automatically stripped from the browser bundle — never ships to the client.
export const metadata = {
  title: 'React for Cross-Platform',
  description: 'One codebase. Six platforms. Zero boilerplate. Write React, ship everywhere.',
keywords: [
    'Bini.js',
    'Bini',
    'bini',
    'bini.js',
    'Bini framework',
    'bini framework',
    'Bini.js framework',
    'bini.js framework',
    'React framework',
    'cross-platform React',
    'cross-platform framework',
    'React SPA framework',
    'zero-config React',
    'full-stack React',
    'meta-framework',
    'modern web framework',
    'file-based routing',
    'Hono API',
    'API routes',
    'SPA',
    'single page application',
    'cross-platform',
    'native apps',
    'native desktop',
    'native mobile',
    'Windows app',
    'macOS app',
    'Linux app',
    'Android app',
    'iOS app',
    'Tauri',
    'desktop application',
    'mobile application',
    'native binary',
    'single codebase',
    'write once run anywhere',
    'Vite',
    'React',
    'TypeScript',
    'JavaScript',
    'Rust',
    'Tailwind CSS',
    'CSS Modules',
    'Oxlint',
    'Oxfmt',
    'Rolldown',
    'deployment',
    'edge functions',
    'Cloudflare Workers',
    'Vercel',
    'Netlify',
    'Deno',
    'Bun',
    'Node.js',
    'static export',
    'SPA deployment',
    'bini-router',
    'bini-env',
    'bini-native',
    'bini-server',
    'bini-overlay',
    'bini-export',
    'create-bini-app',
    'developer experience',
    'DX',
    'zero config',
    'fast development',
    'HMR',
    'hot module replacement',
    'build tool',
    'frontend framework',
    'full-stack framework',
    'open source framework',
    'MIT licensed',
    'Binidu Ranasinghe',
  ],
  themeColor: '#00CFFF',
  manifest: '/site.webmanifest',
  openGraph: {
    title: 'React for Cross-Platform',
    description: 'One codebase. Six platforms. Zero boilerplate. Write React, ship everywhere.',
    images: [{ url: '/og-image.png', width: 1200, height: 630 }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'React for Cross-Platform',
    creator: '@binidu01',
    images: ['/og-image.png'],
  },
  icons: {
    icon: [{ url: '/favicon.ico', type: 'image/x-icon' }],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180' }],
  },
}

// Root layout — wraps every page.
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <React.Fragment>{children}</React.Fragment>
}
